### ISSUE TITLE
Database connection - password needed

### ISSUE THREAD

**Issue by ghost** [simplificuk/docker-nginx-processmaker#1]
Cheers,

I tried to 'install' the docker container, unfortunately there is no information about the initial database password. Could you post this one?

Thanks & Regards,
Jan

**Comment by jlaw90** [comment]
Hi Jan,

There is no database included with this image, just the application itself.  You will need to have a separate docker container running MySQL and link it to the ProcessMaker container upon creation.
e.g. If you had a MySQL container running called processmaker-db, you would add `--link processmaker-db:db` to your docker run command, and then enter 'db' as the hostname when setting up ProcessMaker.

Thanks,
James
